### ISSUE TITLE
Regression introduced by last update

### ISSUE THREAD

**Issue by aebe** [jgoldshlag/crespy#2]
Running sample.py with the current version of the code results in the following error (under Python 2.7.5):

```
Traceback (most recent call last):
  File "sample.py", line 16, in <module>
    for item in prices['items']:
  File "C:\Users\Jonathan\Documents\EVE\crespy-master\crespy-master\crespy.py",
line 42, in __getitem__
    child._headers = self._headers
AttributeError: 'list' object has no attribute '_headers'
```

I'm not sure why we need headers if the child is not a href, but if we really need to keep them we need to make child a class which has a _headers attribute defined.

**Comment by jgoldshlag** [comment]
This should be fixed now, though I haven't tried auth CREST, so I am not sure this fixes the original issue
